// <auto-generated />
using System;
using Libirary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Libirary.Migrations
{
    [DbContext(typeof(LibDBContext))]
    partial class LibDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Libirary.Models.Book", b =>
                {
                    b.Property<Guid>("BSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("autorName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("availableCopiesToborrow")
                        .HasColumnType("int");

                    b.Property<string>("bookTitle")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("borrowed")
                        .HasColumnType("int");

                    b.Property<int?>("copies")
                        .HasColumnType("int");

                    b.HasKey("BSN");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
